apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ala-logger.fullname" . }}-pdb
  labels:
    {{- include "ala-logger.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "ala-logger.selectorLabels" . | nindent 6 }}