apiVersion: v1
kind: Service
metadata:
  name: svc-{{ include "ala-logger.fullname" . }}
  labels:
    {{- include "ala-logger.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: {{ include "ala-logger.resourceTags" . | quote }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort}}
      protocol: TCP
  selector:
    {{- include "ala-logger.selectorLabels" . | nindent 4 }}