openapi: 3.0.1
info:
  title: Logger REST services
  description: REST services for interacting with the logger webapp
  termsOfService: https://www.ala.org.au/terms
  contact:
    name: Support
    email: support@ala.org.au
  license:
    name: Mozilla Public License 1.1
    url: https://www.mozilla.org/en-US/MPL/1.1/
  version: "@info.app.version@"
servers:
  - url: http://devt.ala.org.au:8080
paths:
  "/service/logger/reasons":
    get:
      tags:
        - logger
      summary: Get Reason Types
      description: Get Reason Types
      operationId: Get Reason Types
      responses:
        '200':
          description: Get Reason Types