version: 0.2

env:
  shell: bash
  variables:
    JAVA_TOOL_OPTIONS: -Dhttps.protocols=TLSv1.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - cat /etc/lsb-release
      - apt update -y
        && apt-get -q -y install openjdk-17-jdk
        && pip3 install jinja2
        && curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        && chmod 700 get_helm.sh
        && ./get_helm.sh

  build:
    commands:
      - echo Build started on $(date)
      - aws eks --region ap-southeast-2 update-kubeconfig --name $EKS_CLUSTER_NAME
      - kubectl config set-context --current --namespace=$EKS_NAMESPACE
      - echo "Creating service account for logger..."
      - |
        LOGGER_ROLE_ARN=$(aws cloudformation describe-stacks --stack-name $BASE_STACK_NAME \
          --query "Stacks[0].Outputs[?OutputKey=='LoggerRoleArn'].OutputValue" --output text)
      - printf "$(kubectl config current-context)\n"
      - |
        eksctl create iamserviceaccount --name logger-service-account-$CLEAN_BRANCH \
          --namespace $EKS_NAMESPACE --cluster $EKS_CLUSTER_NAME --attach-role-arn $LOGGER_ROLE_ARN \
          --approve --override-existing-serviceaccounts \
          --tags "product=logger,environment=development,branch=${CLEAN_BRANCH}"
      - echo "Service account created."
      - echo "Deploying logger via helm..."
      - cd helm
      - export BUILD_TAG_FROM_ARTIFACT=$(cat "$CODEBUILD_SRC_DIR_BuildTagArtifact/build_tag.txt")
      - |
        helm upgrade --install $HELM_RELEASE_NAME . -n $EKS_NAMESPACE \
          --set image.repository=$ECR_REPO \
          --set image.tag=$BUILD_TAG_FROM_ARTIFACT \
          --set ingress.hostname=$DOMAIN_NAME \
          --set rds.externalName=$DB_WRITE_ENDPOINT \
          --set ingress.certificateArn=$CERTIFICATE_ARN \
          --set secret.name=logger-config-secret-$CLEAN_BRANCH \
          --set serviceAccount.name=logger-service-account-$CLEAN_BRANCH \
          --set rds.name=mysql-rds-$CLEAN_BRANCH \
          -f $CODEBUILD_SRC_DIR_ExportConfigArtifact/helm-values.yaml
      - kubectl rollout restart deployment $HELM_RELEASE_NAME
  post_build:
    commands:
      - echo Post-build phase...
      - echo Build completed on $(date)

artifacts:
  base-directory: $CODEBUILD_SRC_DIR
  files:
    - '**/*'