---
grails:
    profile: web
    codegen:
        defaultPackage: au.org.ala.logger
    config:
        locations:
            #- classpath:plugin.groovy
            - file:/data/logger/config/logger-config.properties
            - file:/data/logger/config/logger-config.yml
            - file:/data/logger/config/logger-config.groovy
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
        description: 'Atlas of Living Australia'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    jmx:
        unique-names: true
    devtools:
        restart:
            exclude:
                - grails-app/views/**
                - grails-app/i18n/**
                - grails-app/conf/**
management:
    endpoints:
        enabled-by-default: false
---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
---
headerAndFooter:
    baseURL: "https://www.ala.org.au/commonui-bs3-2019"
    version: "2"

skin:
    layout: "main"
    orgNameLong: "Atlas of Living Australia"
    orgNameShort: "ALA"
    orgSupportEmail: support@ala.org.au
privacyPolicy: "https://www.ala.org.au/terms-of-use/privacy-policy/"
siteDefaultLanguage: "en"

security:
    cas:
        adminRole: ROLE_ADMIN
        uriFilterPattern: ["/admin","/admin/*", "/alaAdmin/*"]

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect
    username: root
    password: 'password'

environments:
    development:
        grails:
            serverURL: "http://localhost:8080"
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost/logger?autoReconnect=true&connectTimeout=0&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Australia/Sydney
            username: "logger"
            password: "password"
        security:
            cas:
                appServerName: "http://localhost:8080"
    test:
        grails:
            serverURL: "http://dev.ala.org.au"
        dataSource:
            dialect: org.hibernate.dialect.H2Dialect
            dbCreate: create-drop
            driverClassName: org.h2.Driver
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
        security:
            cas:
                appServerName: "http://dev.ala.org.au"
    production:
        grails:
            serverURL: "https://logger.ala.org.au"
        dataSource:
            dbCreate: none
            url: jdbc:mysql://localhost/logger?autoReconnect=true&connectTimeout=0&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Australia/Sydney
        security:
            cas:
                appServerName: "https://logger.ala.org.au"


security:
    cas:
        enabled: false
    oidc:
        enabled: true
        discoveryUri: https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_8pKx9BtGz/.well-known/openid-configuration
        scope: openid profile email ala/attrs ala/roles
        logoutUrl: https://auth-secure-auth-dev.auth.ap-southeast-2.amazoncognito.com/logout
        logoutAction: cognito
    core:
        roleAttribute: ala:role

    # this config is used to check incoming requests to protected APIs (methods protected with @RequireApiKey()) for JWT token in the expected header i.e. "Authorization". `fallbackToLegacyBehaviour` determines whether to check for the legacy API key when JWT is not detected/valid.
    jwt:
        discoveryUri: https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_8pKx9BtGz/.well-known/openid-configuration
        enabled: true
        fallbackToLegacyBehaviour: true
        userIdClaim: username
        roleClaims: cognito:groups
    apikey:
        enabled: true
        auth:
            serviceUrl: https://auth.ala.org.au/apikey/ws/check/
        check:
            serviceUrl: https://auth.ala.org.au/apikey/ws/check?apikey=
        userdetails:
            serviceUrl: https://auth.ala.org.au/userdetails/userDetails/
openapi:
    title: Logger REST services
    description: REST services for interacting with the logger webapp
    terms: https://www.ala.org.au/terms
    contact:
        name: Support
        email: support@ala.org.au
    license:
        name: Mozilla Public License 1.1
        url: https://www.mozilla.org/en-US/MPL/1.1/
    version: '@info.app.version@'
    cachetimeoutms: 0

webservice:
    jwt: true